//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudSluzba.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudSluzba.Properties.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add department.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add professor.
        /// </summary>
        public static string AddProfessor {
            get {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add student.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add subject.
        /// </summary>
        public static string AddSubject {
            get {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress - number*.
        /// </summary>
        public static string AdressB {
            get {
                return ResourceManager.GetString("AdressB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress - country*.
        /// </summary>
        public static string AdressD {
            get {
                return ResourceManager.GetString("AdressD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress - city*.
        /// </summary>
        public static string AdressG {
            get {
                return ResourceManager.GetString("AdressG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work adress - number*.
        /// </summary>
        public static string AdressKB {
            get {
                return ResourceManager.GetString("AdressKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work adress - country*.
        /// </summary>
        public static string AdressKD {
            get {
                return ResourceManager.GetString("AdressKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work adress - city*.
        /// </summary>
        public static string AdressKG {
            get {
                return ResourceManager.GetString("AdressKG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work adress - street*.
        /// </summary>
        public static string AdressKU {
            get {
                return ResourceManager.GetString("AdressKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress - street*.
        /// </summary>
        public static string AdressU {
            get {
                return ResourceManager.GetString("AdressU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average grade.
        /// </summary>
        public static string AverageGrade {
            get {
                return ResourceManager.GetString("AverageGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average grade:  .
        /// </summary>
        public static string AverageGrade1 {
            get {
                return ResourceManager.GetString("AverageGrade1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss.
        /// </summary>
        public static string Boss {
            get {
                return ResourceManager.GetString("Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss of department*.
        /// </summary>
        public static string BossDepartment1 {
            get {
                return ResourceManager.GetString("BossDepartment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose boss of the department.
        /// </summary>
        public static string ChoseBossDepartment {
            get {
                return ResourceManager.GetString("ChoseBossDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose department.
        /// </summary>
        public static string ChoseDepartment {
            get {
                return ResourceManager.GetString("ChoseDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose professor.
        /// </summary>
        public static string ChoseProfessor {
            get {
                return ResourceManager.GetString("ChoseProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code*.
        /// </summary>
        public static string Code1 {
            get {
                return ResourceManager.GetString("Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth*.
        /// </summary>
        public static string DateBirth {
            get {
                return ResourceManager.GetString("DateBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete grade.
        /// </summary>
        public static string DeleteGrade {
            get {
                return ResourceManager.GetString("DeleteGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subject.
        /// </summary>
        public static string DeleteSubject {
            get {
                return ResourceManager.GetString("DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department*.
        /// </summary>
        public static string Department1 {
            get {
                return ResourceManager.GetString("Department1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit department.
        /// </summary>
        public static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit professor.
        /// </summary>
        public static string EditProfessor {
            get {
                return ResourceManager.GetString("EditProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit student.
        /// </summary>
        public static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit subject.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adress.
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adress*.
        /// </summary>
        public static string EmailAdress1 {
            get {
                return ResourceManager.GetString("EmailAdress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB.
        /// </summary>
        public static string ESPB {
            get {
                return ResourceManager.GetString("ESPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB*.
        /// </summary>
        public static string ESPB1 {
            get {
                return ResourceManager.GetString("ESPB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPB in total:  .
        /// </summary>
        public static string ESPBTotal {
            get {
                return ResourceManager.GetString("ESPBTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed exams.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name* .
        /// </summary>
        public static string FirstName1 {
            get {
                return ResourceManager.GetString("FirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card*.
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index*.
        /// </summary>
        public static string Index1 {
            get {
                return ResourceManager.GetString("Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name*.
        /// </summary>
        public static string LastName1 {
            get {
                return ResourceManager.GetString("LastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed exams.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number*.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor*.
        /// </summary>
        public static string Professor1 {
            get {
                return ResourceManager.GetString("Professor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professors.
        /// </summary>
        public static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester*.
        /// </summary>
        public static string Semester1 {
            get {
                return ResourceManager.GetString("Semester1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing*.
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student service.
        /// </summary>
        public static string StudentService {
            get {
                return ResourceManager.GetString("StudentService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title*.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year*.
        /// </summary>
        public static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of admission*.
        /// </summary>
        public static string YearAdmission {
            get {
                return ResourceManager.GetString("YearAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of study.
        /// </summary>
        public static string YearOfStudy {
            get {
                return ResourceManager.GetString("YearOfStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of study*.
        /// </summary>
        public static string YearOfStudy1 {
            get {
                return ResourceManager.GetString("YearOfStudy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of service*.
        /// </summary>
        public static string YearsService {
            get {
                return ResourceManager.GetString("YearsService", resourceCulture);
            }
        }
    }
}
